// Banco de preguntas por carrera.
// Cada pregunta: q = enunciado, a = respuesta correcta, w = tres respuestas incorrectas.
// El orden de las opciones se mezcla en cada partida, así que la correcta puede ir siempre en `a`.

const CARRERAS = [
  {
    id: "turismo",
    nombre: "Turismo",
    emoji: "✈️",
    color: "#FF8A5B",
    preguntas: [
      { q: "¿Qué puede hacer un chatbot con IA en la web de una agencia de viajes?", a: "Responder consultas de los viajeros las 24 horas", w: ["Emitir pasaportes", "Pilotear el avión", "Cambiar el clima del destino"] },
      { q: "Cuando una app te recomienda destinos según tus viajes anteriores, ¿qué está usando?", a: "Un sistema de recomendación con IA", w: ["Una brújula digital", "Un mapa en papel", "Una calculadora de distancias"] },
      { q: "¿Qué herramienta con IA te ayuda a entender un menú en otro idioma apuntándole con la cámara?", a: "Un traductor que reconoce imágenes, como Google Lens", w: ["Un termómetro", "Una linterna", "Un podómetro"] },
      { q: "Las aerolíneas usan IA para cambiar el precio de los pasajes según la demanda. ¿Cómo se llama eso?", a: "Precios dinámicos", w: ["Precios congelados", "Tarifa plana", "Trueque"] },
      { q: "Si le pedís a ChatGPT \"armame un itinerario de 3 días en Salta\", ¿qué tipo de IA estás usando?", a: "IA generativa", w: ["Una IA que maneja autos", "Un robot de limpieza", "Una alarma"] },
      { q: "¿Qué conviene hacer con un itinerario que te armó una IA?", a: "Revisar horarios y datos, porque puede equivocarse", w: ["Confiar al 100% sin mirar nada", "Imprimirlo sin leerlo", "Compartirlo sin revisarlo"] },
      { q: "¿Para qué puede usar IA una oficina de turismo al leer miles de reseñas en internet?", a: "Para saber qué opinan los visitantes y mejorar", w: ["Para borrar todas las reseñas", "Para inventar turistas", "Para cerrar la oficina"] },
      { q: "¿Cómo puede la IA estimar cuántos turistas llegarán en temporada alta?", a: "Analizando datos de años anteriores y reservas", w: ["Tirando una moneda", "Preguntándole a un solo turista", "Es imposible estimarlo"] },
      { q: "En los aeropuertos, el reconocimiento facial con IA se usa para…", a: "Agilizar el control de identidad y el embarque", w: ["Elegir la comida del avión", "Pintar los aviones", "Pesar el equipaje"] },
      { q: "¿Qué significa que una IA \"personalice\" una oferta de viaje?", a: "Que la adapta a los gustos de cada persona", w: ["Que es igual para todos", "Que siempre la hace más cara", "Que la escribe a mano"] },
      { q: "Una IA que traduce en tiempo real una charla con un turista extranjero ayuda a…", a: "Superar la barrera del idioma", w: ["Aprender a nadar", "Conseguir vuelos gratis", "Evitar hablar con turistas"] },
      { q: "¿Qué NO deberías pegar en un chatbot cualquiera mientras planeás un viaje?", a: "Tu número de pasaporte y los datos de tu tarjeta", w: ["El destino que querés visitar", "Tus fechas tentativas", "Tu presupuesto aproximado"] },
      { q: "Plataformas como Booking o Airbnb usan IA para…", a: "Ordenar y recomendar alojamientos según lo que buscás", w: ["Construir hoteles", "Sacar fotos de los destinos en persona", "Manejar taxis"] },
      { q: "¿Qué es una \"alucinación\" de la IA al planificar un viaje?", a: "Cuando inventa datos que parecen reales, como un museo que no existe", w: ["Cuando te recomienda descansar", "Cuando se queda sin batería", "Cuando muestra fotos lindas"] },
      { q: "Una app que te avisa que un lugar turístico va a estar lleno a cierta hora está usando IA para…", a: "Predecir la cantidad de gente y ayudarte a elegir otro horario", w: ["Cerrar el lugar", "Cobrarte la entrada", "Sacarte una foto"] },
    ],
  },
  {
    id: "hoteleria",
    nombre: "Hotelería",
    emoji: "🛎️",
    color: "#E0699A",
    preguntas: [
      { q: "Un chatbot con IA en el WhatsApp del hotel puede…", a: "Responder a los huéspedes y tomar reservas a toda hora", w: ["Hacer las camas", "Cocinar el desayuno", "Arreglar las canillas"] },
      { q: "El check-in con reconocimiento facial sirve para…", a: "Registrar al huésped más rápido", w: ["Elegir el color de las sábanas", "Limpiar la habitación", "Calentar la pileta"] },
      { q: "Los hoteles usan IA para ajustar la tarifa según la ocupación y la demanda. ¿Cómo se llama?", a: "Revenue management (precios dinámicos)", w: ["Tarifa fija para siempre", "Descuento obligatorio", "Precio al azar"] },
      { q: "Un asistente de voz en la habitación puede…", a: "Encender luces, pedir room service o responder dudas", w: ["Hacer el check-out de otros huéspedes", "Pagar los sueldos", "Pintar la habitación"] },
      { q: "¿Para qué sirve analizar con IA miles de reseñas en Google o TripAdvisor?", a: "Para detectar qué les gusta y qué no a los huéspedes", w: ["Para subir el precio del minibar", "Para borrar las críticas malas", "Para contratar gente sin motivo"] },
      { q: "La IA puede predecir cuántos desayunos preparar según la ocupación. ¿Qué se logra?", a: "Tirar menos comida", w: ["Tirar más comida", "Desayunos más fríos", "Nada, no sirve"] },
      { q: "Un robot que lleva toallas o pedidos hasta las habitaciones es un ejemplo de…", a: "Robótica de servicio con IA", w: ["Recepción tradicional", "Un ascensor común", "Una aspiradora manual"] },
      { q: "Si una IA redacta la respuesta a una reseña negativa, ¿qué conviene hacer?", a: "Revisarla y personalizarla antes de publicarla", w: ["Publicarla sin leer", "Contestar con enojo", "Ignorar la reseña para siempre"] },
      { q: "Sensores inteligentes que apagan el aire acondicionado cuando no hay nadie en la habitación sirven para…", a: "Ahorrar energía", w: ["Gastar más", "Hacer más ruido", "Nada"] },
      { q: "¿Qué es la personalización en hotelería con IA?", a: "Recordar preferencias del huésped, como su almohada o bebida favorita", w: ["Tratar a todos igual sin datos", "Cambiar el nombre del hotel", "Cobrar siempre lo mismo"] },
      { q: "La IA que traduce al instante entre la recepción y un huésped extranjero mejora…", a: "La atención y la comunicación", w: ["El tamaño de las habitaciones", "El precio del estacionamiento", "La velocidad del ascensor"] },
      { q: "¿Qué cuidado hay que tener con los datos de los huéspedes al usar IA?", a: "Protegerlos y no compartirlos sin permiso", w: ["Publicarlos en redes", "Venderlos", "Dejarlos a la vista en la recepción"] },
      { q: "Usar IA para anticipar qué equipos del hotel se van a romper antes de que fallen se llama…", a: "Mantenimiento predictivo", w: ["Mantenimiento mágico", "Limpieza express", "Check-out anticipado"] },
      { q: "¿La IA reemplaza por completo la calidez humana en un hotel?", a: "No: ayuda, pero el trato humano sigue siendo clave", w: ["Sí, ya no hace falta nadie", "Sí, todos los huéspedes prefieren robots", "La IA no se puede usar en hoteles"] },
      { q: "Una IA que le sugiere al huésped un spa o una cena especial según su perfil está haciendo…", a: "Venta personalizada (upselling)", w: ["Limpieza", "Contabilidad", "Vigilancia"] },
    ],
  },
  {
    id: "logistica",
    nombre: "Logística",
    emoji: "📦",
    color: "#F2B233",
    preguntas: [
      { q: "¿Cómo ayuda la IA a un camión de reparto?", a: "Calculando la ruta más rápida según el tránsito", w: ["Inflando las cubiertas", "Cargando combustible", "Lavando el camión"] },
      { q: "Predecir cuántos productos se van a vender el mes que viene se llama…", a: "Pronóstico de demanda", w: ["Inventario congelado", "Despacho aduanero", "Embalaje"] },
      { q: "En un depósito, los robots con IA que mueven estanterías sirven para…", a: "Preparar pedidos más rápido", w: ["Decorar el depósito", "Llevar la contabilidad", "Atender el teléfono"] },
      { q: "Cuando una app te dice \"tu pedido llega entre las 14 y las 15\", ¿con qué lo calculó?", a: "Con datos de tránsito, distancia y entregas anteriores", w: ["Con una bola de cristal", "Con el horóscopo", "Con un número al azar"] },
      { q: "¿Qué es un vehículo autónomo?", a: "Un vehículo que se maneja solo usando sensores e IA", w: ["Un camión sin ruedas", "Un auto que solo anda de noche", "Una bicicleta eléctrica"] },
      { q: "Una cámara con IA sobre una cinta transportadora puede…", a: "Detectar paquetes dañados o mal etiquetados", w: ["Pintar las cajas", "Pesar al operario", "Poner música"] },
      { q: "En logística, los drones con IA se usan para…", a: "Hacer entregas rápidas o contar inventario en depósitos", w: ["Reemplazar barcos", "Fabricar cajas", "Firmar remitos"] },
      { q: "Si la IA predice bien la demanda, ¿qué se evita?", a: "Quedarse sin stock o tener mercadería de más", w: ["Vender productos", "Tener clientes", "Usar camiones"] },
      { q: "¿Qué beneficio ambiental tiene optimizar rutas con IA?", a: "Menos kilómetros recorridos y menos emisiones", w: ["Más contaminación", "Camiones más pesados", "Ninguno"] },
      { q: "El mantenimiento predictivo de una flota de camiones consiste en…", a: "Anticipar fallas antes de que el camión se rompa", w: ["Esperar a que se rompa", "Cambiar todos los camiones cada mes", "Lavar los camiones seguido"] },
      { q: "Un chatbot que responde \"¿dónde está mi envío?\" ayuda a…", a: "Bajar las consultas al centro de atención", w: ["Aumentar los reclamos", "Perder paquetes", "Frenar las entregas"] },
      { q: "Leer automáticamente facturas y remitos escaneados se hace con…", a: "Reconocimiento de texto con IA (OCR)", w: ["Una fotocopiadora", "Una impresora 3D", "Código Morse"] },
      { q: "¿Qué necesita una IA para predecir bien la demanda?", a: "Datos históricos de buena calidad", w: ["Nada, adivina sola", "Solo una foto del depósito", "Un camión nuevo"] },
      { q: "Un \"gemelo digital\" de un depósito es…", a: "Una copia virtual para probar cambios antes de hacerlos en la realidad", w: ["Un segundo depósito igual construido al lado", "Un empleado parecido a otro", "Una cámara de seguridad"] },
      { q: "Ante un problema grave en la cadena de suministro, ¿quién debería tomar la decisión final?", a: "Una persona, apoyada con la información de la IA", w: ["Solo la IA, sin supervisión", "Nadie", "El proveedor más barato"] },
    ],
  },
  {
    id: "seguridad",
    nombre: "Seguridad e Higiene",
    emoji: "⛑️",
    color: "#3BB273",
    preguntas: [
      { q: "Una cámara con IA en una obra puede detectar si un trabajador…", a: "No tiene puesto el casco o el chaleco", w: ["Está contento", "Tiene hambre", "Llegó en colectivo"] },
      { q: "Los sensores inteligentes que miden gases en una planta sirven para…", a: "Avisar antes de que el ambiente sea peligroso", w: ["Perfumar el ambiente", "Medir la música", "Contar empleados"] },
      { q: "Analizar con IA los accidentes que ya ocurrieron en una empresa ayuda a…", a: "Prevenir que vuelvan a pasar", w: ["Ocultarlos", "Aumentar los riesgos", "Nada"] },
      { q: "Un reloj o pulsera inteligente en un trabajador puede…", a: "Detectar caídas o cansancio y dar aviso", w: ["Hacer la tarea por él", "Pagarle el sueldo", "Cambiarle el turno solo"] },
      { q: "¿Qué es el mantenimiento predictivo en seguridad industrial?", a: "Usar datos e IA para detectar fallas en máquinas antes de que causen un accidente", w: ["Arreglar las máquinas solo cuando se rompen", "Apagar todo los viernes", "Pintar las máquinas"] },
      { q: "Un chatbot con IA sirve para capacitar en seguridad porque…", a: "Responde dudas sobre normas y procedimientos en cualquier momento", w: ["Reemplaza los elementos de protección", "Firma los permisos de trabajo", "Apaga incendios"] },
      { q: "Simular con IA la evacuación de un edificio sirve para…", a: "Encontrar las mejores rutas de escape y los cuellos de botella", w: ["Decorar las salidas", "No hacer nunca más simulacros reales", "Cerrar las puertas"] },
      { q: "Si la IA detecta una zona peligrosa, ¿quién decide qué medidas tomar?", a: "El responsable de seguridad, con la información de la IA", w: ["Nadie", "La cámara sola", "Los visitantes"] },
      { q: "Un dron con cámara térmica e IA en una inspección permite…", a: "Revisar lugares altos o peligrosos sin exponer a personas", w: ["Repartir el almuerzo", "Sacar fotos para redes", "Reemplazar a los matafuegos"] },
      { q: "¿Por qué conviene que la IA analice los \"casi accidentes\"?", a: "Porque muestran riesgos antes de que alguien se lastime", w: ["Porque no importan", "Porque son feriados", "Porque son fallas del sistema"] },
      { q: "Una IA que mide el ruido en una fábrica puede avisar cuando…", a: "Se superan niveles que dañan la audición", w: ["Suena el timbre del almuerzo", "Alguien canta", "Termina el turno"] },
      { q: "¿Qué cuidado hay que tener con las cámaras de IA que monitorean a los trabajadores?", a: "Respetar su privacidad y explicarles para qué se usan", w: ["Esconderlas", "Usarlas para hacer chistes", "Publicar los videos"] },
      { q: "Una IA te genera un checklist de seguridad para una tarea. ¿Qué hacés?", a: "Lo reviso con un profesional antes de usarlo", w: ["Lo uso sin leerlo", "Lo tiro", "Lo firmo sin revisarlo"] },
      { q: "Detectar con visión artificial que alguien entra en una zona con máquinas en movimiento permite…", a: "Frenar la máquina o dar la alerta a tiempo", w: ["Acelerar la máquina", "Sacar una foto de recuerdo", "Nada"] },
      { q: "Un sistema de IA que analiza videos de un trabajador en su puesto puede…", a: "Detectar posturas que pueden causar lesiones", w: ["Elegirle la ropa", "Medir su simpatía", "Contar sus pasos de baile"] },
    ],
  },
  {
    id: "rrhh",
    nombre: "Recursos Humanos",
    emoji: "🤝",
    color: "#8E6CEF",
    preguntas: [
      { q: "Un software con IA que lee cientos de CVs puede…", a: "Ayudar a filtrar candidatos según los requisitos del puesto", w: ["Contratar sin que nadie revise", "Pagar los sueldos", "Hacer la entrevista presencial"] },
      { q: "¿Qué riesgo tiene usar IA para seleccionar personal?", a: "Que repita sesgos o discriminaciones de los datos con los que aprendió", w: ["Que lea demasiado rápido", "Que gaste mucha tinta", "Ninguno"] },
      { q: "Un chatbot interno de RRHH puede responder…", a: "Consultas sobre vacaciones, licencias y recibos de sueldo", w: ["Quién gana el próximo partido", "Cómo arreglar el auto", "Qué almorzar"] },
      { q: "Usar IA para escribir un aviso de búsqueda laboral sirve para…", a: "Redactarlo más rápido, aunque hay que revisarlo", w: ["Garantizar el mejor candidato", "No leer ningún CV", "Evitar las entrevistas"] },
      { q: "La IA puede analizar encuestas de clima laboral para…", a: "Detectar los temas que preocupan a los empleados", w: ["Buscar quién se quejó y castigarlo", "Aumentar las horas extra", "Nada"] },
      { q: "¿Qué es un onboarding asistido por IA?", a: "Acompañar a quien entra a la empresa con guías e información automáticas", w: ["Despedir empleados", "Pagar el aguinaldo", "Organizar el asado de fin de año"] },
      { q: "Usar datos para predecir qué empleados podrían renunciar es un análisis de…", a: "Rotación de personal", w: ["Ventas", "Tránsito", "Pronóstico del tiempo"] },
      { q: "¿Quién debe tomar la decisión final de contratar a alguien?", a: "Una persona, usando la IA solo como apoyo", w: ["Solo la IA", "El mismo candidato", "Un sorteo"] },
      { q: "Una plataforma de capacitación con IA puede…", a: "Recomendar cursos según las habilidades de cada empleado", w: ["Dar el mismo curso a todos sin importar nada", "Rendir los exámenes por vos", "Tomarse vacaciones"] },
      { q: "¿Qué datos de los empleados hay que proteger especialmente al usar IA?", a: "Datos personales como sueldo, salud y documentos", w: ["El nombre de la empresa", "El horario del comedor", "El color de la oficina"] },
      { q: "Un candidato usa IA para mejorar la redacción de su CV. ¿Está mal?", a: "No, está bien si la información es verdadera", w: ["Sí, siempre está prohibido", "Sí, anula la postulación", "Solo si el CV es largo"] },
      { q: "Las entrevistas por video evaluadas por IA generan debate porque…", a: "Pueden ser injustas si juzgan gestos, acento o apariencia", w: ["Son muy cortas", "Usan mucha luz", "No tienen sonido"] },
      { q: "Con la llegada de la IA, ¿qué habilidad se vuelve más valiosa en RRHH?", a: "La empatía y el trato humano", w: ["Escribir a máquina", "Archivar papeles", "Sacar fotocopias"] },
      { q: "¿Qué es \"people analytics\"?", a: "Usar datos para tomar mejores decisiones sobre las personas de la empresa", w: ["Una red social de empleados", "Un tipo de contrato", "Un reloj para fichar"] },
      { q: "Si una IA sugiere un rango salarial para un puesto, conviene…", a: "Compararlo con el mercado y las políticas de la empresa", w: ["Aceptarlo sin revisar", "Duplicarlo", "Ignorar el puesto"] },
    ],
  },
  {
    id: "datos",
    nombre: "Ciencia de Datos e IA",
    emoji: "🤖",
    color: "#2F9BD7",
    preguntas: [
      { q: "¿Qué significa \"IA\"?", a: "Inteligencia Artificial", w: ["Información Automática", "Internet Avanzada", "Interfaz Animada"] },
      { q: "¿Qué es el machine learning?", a: "Que las computadoras aprendan patrones a partir de datos", w: ["Arreglar máquinas", "Programar lavarropas", "Aprender a manejar"] },
      { q: "ChatGPT, Claude y Gemini son ejemplos de…", a: "Modelos de lenguaje (LLM)", w: ["Sistemas operativos", "Antivirus", "Planillas de cálculo"] },
      { q: "¿Qué es un dataset?", a: "Un conjunto de datos", w: ["Un tipo de computadora", "Un lenguaje de programación", "Un cable"] },
      { q: "¿Cuál es el lenguaje de programación más usado en ciencia de datos?", a: "Python", w: ["HTML", "Morse", "Latín"] },
      { q: "¿Qué es un prompt?", a: "La instrucción o pregunta que le das a una IA", w: ["Un virus", "Un tipo de gráfico", "Una contraseña"] },
      { q: "Cuando una IA inventa una respuesta falsa pero convincente, se dice que…", a: "Alucina", w: ["Duerme", "Se actualiza", "Se reinicia"] },
      { q: "Si entrenás una IA con datos sesgados, el resultado probablemente será…", a: "Sesgado también", w: ["Perfecto", "Siempre neutral", "Más rápido"] },
      { q: "¿Qué gráfico conviene para ver cómo cambian las ventas mes a mes?", a: "Un gráfico de líneas", w: ["Un gráfico de torta", "Una foto", "Una tabla sin números"] },
      { q: "¿Qué hace la visión por computadora?", a: "Permite que la IA interprete imágenes y videos", w: ["Mejora la vista de las personas", "Limpia la pantalla", "Sube el brillo"] },
      { q: "Separar los datos en \"entrenamiento\" y \"prueba\" sirve para…", a: "Comprobar si el modelo funciona con datos que no vio", w: ["Ahorrar espacio", "Borrar datos", "Que quede más lindo"] },
      { q: "¿Qué es la IA generativa?", a: "IA que crea contenido nuevo: textos, imágenes o música", w: ["IA que genera electricidad", "IA que borra archivos", "Un generador de contraseñas"] },
      { q: "Antes de analizar datos hay que \"limpiarlos\". ¿Qué significa?", a: "Corregir errores, duplicados y valores faltantes", w: ["Pasarles un trapo", "Borrarlos todos", "Imprimirlos"] },
      { q: "¿Qué es un algoritmo?", a: "Una serie de pasos para resolver un problema", w: ["Un tipo de robot", "Una marca de computadoras", "Un idioma"] },
      { q: "¿Qué es Big Data?", a: "Volúmenes enormes de datos, difíciles de manejar con herramientas comunes", w: ["Una computadora muy grande", "Un disco rígido gigante", "Una red social"] },
    ],
  },
];
