// Banco de preguntas por carrera.
// Cada pregunta: q = enunciado, a = respuesta correcta,
// w = incorrectas: la primera es la que confunde, las otras dos son graciosas.
// El orden de las opciones se mezcla en cada partida.

const CARRERAS = [
  {
    id: "turismo",
    nombre: "Turismo",
    emoji: "✈️",
    color: "#FF8A5B",
    preguntas: [
      { q: "¿Qué puede hacer un chatbot con IA en la web de una agencia de viajes?", a: "Responder consultas de los viajeros las 24 horas", w: ["Garantizar que los vuelos nunca se atrasen", "Emitir pasaportes con una selfie", "Hacerte la valija"] },
      { q: "Cuando una app te recomienda destinos según tus viajes anteriores, ¿qué está usando?", a: "Un sistema de recomendación con IA", w: ["El GPS del celular", "Una brújula con wifi", "Tu tía que ya fue a todos lados"] },
      { q: "¿Qué herramienta con IA te ayuda a entender un menú en otro idioma apuntándole con la cámara?", a: "Un traductor que reconoce imágenes, como Google Lens", w: ["Un lector de códigos QR", "Un termómetro", "Una linterna muy potente"] },
      { q: "Las aerolíneas usan IA para cambiar el precio de los pasajes según la demanda. ¿Cómo se llama eso?", a: "Precios dinámicos", w: ["Precios promocionales", "Precios al voleo", "Trueque de pasajes por empanadas"] },
      { q: "Si le pedís a ChatGPT \"armame un itinerario de 3 días en Salta\", ¿qué tipo de IA estás usando?", a: "IA generativa", w: ["Un buscador tradicional", "Una IA que maneja colectivos", "Magia"] },
      { q: "¿Qué conviene hacer con un itinerario que te armó una IA?", a: "Revisar horarios y datos, porque puede equivocarse", w: ["Usarlo tal cual, porque la IA siempre tiene datos actualizados", "Imprimirlo y enmarcarlo", "Leérselo a las plantas"] },
      { q: "¿Para qué puede usar IA una oficina de turismo al leer miles de reseñas en internet?", a: "Para saber qué opinan los visitantes y mejorar", w: ["Para ocultar automáticamente las reseñas negativas", "Para inventar turistas felices", "Para contestar todas con memes"] },
      { q: "¿Cómo puede la IA estimar cuántos turistas llegarán en temporada alta?", a: "Analizando datos de años anteriores y reservas", w: ["Contando cuánta gente hay hoy en la terminal", "Tirando una moneda", "Leyendo el horóscopo"] },
      { q: "En los aeropuertos, el reconocimiento facial con IA se usa para…", a: "Agilizar el control de identidad y el embarque", w: ["Calcular el peso del equipaje", "Elegir tu mejor foto para Instagram", "Detectar si tenés cara de vacaciones"] },
      { q: "¿Qué significa que una IA \"personalice\" una oferta de viaje?", a: "Que la adapta a los gustos de cada persona", w: ["Que le pone tu nombre al mail, aunque la oferta sea igual para todos", "Que te la canta por teléfono", "Que la escribe a mano con pluma"] },
      { q: "Una IA que traduce en tiempo real una charla con un turista extranjero ayuda a…", a: "Superar la barrera del idioma", w: ["Aprender el idioma sin esfuerzo", "Hablar con los delfines", "Conseguir vuelos gratis"] },
      { q: "¿Qué dato es mejor NO darle a un chatbot cualquiera mientras planeás un viaje?", a: "Tu número de pasaporte y los datos de tu tarjeta", w: ["Tu presupuesto aproximado", "Que te gustan las playas", "Que odiás madrugar"] },
      { q: "Plataformas como Booking o Airbnb usan IA para…", a: "Ordenar y recomendar alojamientos según lo que buscás", w: ["Verificar en persona que las fotos sean reales", "Construir hoteles con impresora 3D", "Elegir tu pijama"] },
      { q: "¿Qué es una \"alucinación\" de la IA al planificar un viaje?", a: "Cuando inventa datos que parecen reales, como un museo que no existe", w: ["Cuando tarda mucho en responder", "Cuando ve unicornios", "Cuando se toma vacaciones"] },
      { q: "Una app que te avisa que un lugar turístico va a estar lleno a cierta hora está usando IA para…", a: "Predecir la cantidad de gente y sugerirte otro horario", w: ["Reservarte la entrada automáticamente", "Cerrar el lugar para vos solo", "Sacar a la gente que sobra"] },
    ],
  },
  {
    id: "hoteleria",
    nombre: "Hotelería",
    emoji: "🛎️",
    color: "#E0699A",
    preguntas: [
      { q: "Un chatbot con IA en el WhatsApp del hotel puede…", a: "Responder a los huéspedes y tomar reservas a toda hora", w: ["Reemplazar al recepcionista en todas sus tareas", "Hacer las camas", "Cebarte unos mates"] },
      { q: "El check-in con reconocimiento facial sirve para…", a: "Registrar al huésped más rápido", w: ["Asignar la habitación según la edad del huésped", "Saber si dormiste bien", "Elegir el color de las sábanas"] },
      { q: "Los hoteles usan IA para ajustar la tarifa según la ocupación y la demanda. ¿Cómo se llama?", a: "Revenue management (precios dinámicos)", w: ["Housekeeping", "Tarifa \"según cómo me levanté\"", "Precio al azar con dados"] },
      { q: "Un asistente de voz en la habitación puede…", a: "Encender luces, pedir room service o responder dudas", w: ["Limpiar la habitación mientras no estás", "Contarte los chismes de la habitación de al lado", "Pintar las paredes"] },
      { q: "¿Para qué sirve analizar con IA miles de reseñas en Google o TripAdvisor?", a: "Para detectar qué les gusta y qué no a los huéspedes", w: ["Para responderlas todas sin que nadie las lea", "Para subir el precio del minibar", "Para saber quién se llevó las toallas"] },
      { q: "La IA puede predecir cuántos desayunos preparar según la ocupación. ¿Qué se logra?", a: "Tirar menos comida", w: ["Que el desayuno le salga más barato al huésped", "Medialunas infinitas", "Que el café salga más caliente"] },
      { q: "Un robot que lleva toallas o pedidos hasta las habitaciones es un ejemplo de…", a: "Robótica de servicio con IA", w: ["Automatización de reservas online", "Un mayordomo fantasma", "Una aspiradora con ambiciones"] },
      { q: "Si una IA redacta la respuesta a una reseña negativa, ¿qué conviene hacer?", a: "Revisarla y personalizarla antes de publicarla", w: ["Publicarla directo, así se responde más rápido", "Responder con un sticker", "Contestar todo en mayúsculas"] },
      { q: "Sensores inteligentes que apagan el aire acondicionado cuando no hay nadie en la habitación sirven para…", a: "Ahorrar energía", w: ["Mejorar la señal del wifi", "Que el aire se tome un descanso", "Que el huésped extrañe su casa"] },
      { q: "¿Qué es la personalización en hotelería con IA?", a: "Recordar preferencias del huésped, como su almohada o bebida favorita", w: ["Ofrecerle a todos el mismo paquete, pero con descuento", "Poner una foto del huésped en cada pared", "Cambiarle el nombre al hotel por el tuyo"] },
      { q: "La IA que traduce al instante entre la recepción y un huésped extranjero mejora…", a: "La atención y la comunicación", w: ["La ocupación del hotel", "El tamaño de las habitaciones", "La velocidad del ascensor"] },
      { q: "¿Qué cuidado hay que tener con los datos de los huéspedes al usar IA?", a: "Protegerlos y no compartirlos sin permiso", w: ["Guardarlos todos para siempre, por si algún día sirven", "Publicarlos en la cartelera del lobby", "Dejarlos a la vista en la recepción"] },
      { q: "Usar IA para anticipar qué equipos del hotel se van a romper antes de que fallen se llama…", a: "Mantenimiento predictivo", w: ["Mantenimiento correctivo", "Mantenimiento mágico", "Rezarle al aire acondicionado"] },
      { q: "¿La IA reemplaza por completo la calidez humana en un hotel?", a: "No: ayuda, pero el trato humano sigue siendo clave", w: ["Sí, en unos años los hoteles no van a necesitar personal", "Sí, los robots dan mejores abrazos", "La IA no se lleva bien con los huéspedes"] },
      { q: "Una IA que le sugiere al huésped un spa o una cena especial según su perfil está haciendo…", a: "Venta personalizada (upselling)", w: ["Overbooking", "Brujería comercial", "Adivinación"] },
    ],
  },
  {
    id: "logistica",
    nombre: "Logística",
    emoji: "📦",
    color: "#F2B233",
    preguntas: [
      { q: "¿Cómo ayuda la IA a un camión de reparto?", a: "Calculando la ruta más rápida según el tránsito", w: ["Haciendo que vaya siempre por la misma ruta para no perderse", "Inflando las cubiertas con la mente", "Eligiendo la playlist del chofer"] },
      { q: "Predecir cuántos productos se van a vender el mes que viene se llama…", a: "Pronóstico de demanda", w: ["Control de inventario", "Adivinanza comercial", "Horóscopo de ventas"] },
      { q: "En un depósito, los robots con IA que mueven estanterías sirven para…", a: "Preparar pedidos más rápido", w: ["Reemplazar el sistema de gestión del depósito", "Bailar en la fiesta de fin de año", "Decorar el depósito"] },
      { q: "Cuando una app te dice \"tu pedido llega entre las 14 y las 15\", ¿con qué lo calculó?", a: "Con datos de tránsito, distancia y entregas anteriores", w: ["Con el horario que eligió el repartidor ese día", "Con una bola de cristal", "Con el horóscopo del paquete"] },
      { q: "¿Qué es un vehículo autónomo?", a: "Un vehículo que se maneja solo usando sensores e IA", w: ["Un vehículo eléctrico que no necesita combustible", "Un camión que se va de vacaciones cuando quiere", "Un auto que se lava solo"] },
      { q: "Una cámara con IA sobre una cinta transportadora puede…", a: "Detectar paquetes dañados o mal etiquetados", w: ["Pesar cada paquete", "Envolver los paquetes para regalo", "Poner música para motivar a las cajas"] },
      { q: "En logística, los drones con IA se usan para…", a: "Hacer entregas rápidas o contar inventario en depósitos", w: ["Reemplazar a los camiones en los envíos pesados", "Hacer carreras en el depósito", "Pasear al perro del jefe"] },
      { q: "Si la IA predice bien la demanda, ¿qué se evita?", a: "Quedarse sin stock o tener mercadería de más", w: ["Necesitar proveedores", "Que existan los lunes", "Tener clientes"] },
      { q: "¿Qué beneficio ambiental tiene optimizar rutas con IA?", a: "Menos kilómetros recorridos y menos emisiones", w: ["Usar menos cajas de cartón", "Camiones que plantan árboles", "Ninguno, los camiones son eternos"] },
      { q: "El mantenimiento predictivo de una flota de camiones consiste en…", a: "Anticipar fallas antes de que el camión se rompa", w: ["Hacer el service cada tantos kilómetros, sin mirar datos", "Esperar a que haga un ruido raro", "Hablarle lindo al motor"] },
      { q: "Un chatbot que responde \"¿dónde está mi envío?\" ayuda a…", a: "Bajar las consultas al centro de atención", w: ["Que los paquetes lleguen más rápido", "Perder paquetes con más estilo", "Que el cliente se haga amigo del chatbot"] },
      { q: "Leer automáticamente facturas y remitos escaneados se hace con…", a: "Reconocimiento de texto con IA (OCR)", w: ["Un lector de código de barras", "Código Morse", "Un pasante con lupa"] },
      { q: "¿Qué necesita una IA para predecir bien la demanda?", a: "Datos históricos de buena calidad", w: ["Una computadora muy potente, aunque haya pocos datos", "Nada, adivina sola", "Un camión nuevo"] },
      { q: "Un \"gemelo digital\" de un depósito es…", a: "Una copia virtual para probar cambios antes de hacerlos en la realidad", w: ["Una copia de seguridad de la base de datos", "Un segundo depósito igual construido al lado", "El hermano gemelo del encargado"] },
      { q: "Ante un problema grave en la cadena de suministro, ¿quién debería tomar la decisión final?", a: "Una persona, apoyada con la información de la IA", w: ["La IA, porque analiza más datos que cualquier persona", "El camión más viejo de la flota", "Piedra, papel o tijera"] },
    ],
  },
  {
    id: "seguridad",
    nombre: "Seguridad e Higiene",
    emoji: "⛑️",
    color: "#3BB273",
    preguntas: [
      { q: "Una cámara con IA en una obra puede detectar si un trabajador…", a: "No tiene puesto el casco o el chaleco", w: ["Tiene el carnet de conducir vencido", "Está enamorado", "Llegó en colectivo"] },
      { q: "Los sensores inteligentes que miden gases en una planta sirven para…", a: "Avisar antes de que el ambiente sea peligroso", w: ["Limpiar el aire automáticamente", "Perfumar el ambiente", "Descubrir quién comió huevo duro"] },
      { q: "Analizar con IA los accidentes que ya ocurrieron en una empresa ayuda a…", a: "Prevenir que vuelvan a pasar", w: ["Encontrar a quién echarle la culpa", "Armar un calendario con los mejores sustos", "Nada, lo pasado pisado"] },
      { q: "Un reloj o pulsera inteligente en un trabajador puede…", a: "Detectar caídas o cansancio y dar aviso", w: ["Evitar que el trabajador se caiga", "Hacer la tarea por él", "Contarle chistes cuando se aburre"] },
      { q: "¿Qué es el mantenimiento predictivo en seguridad industrial?", a: "Usar datos e IA para detectar fallas en máquinas antes de que causen un accidente", w: ["Revisar las máquinas una vez por año, pase lo que pase", "Arreglarlas con cinta y fe", "Pintarlas de colores alegres"] },
      { q: "Un chatbot con IA sirve para capacitar en seguridad porque…", a: "Responde dudas sobre normas y procedimientos en cualquier momento", w: ["Reemplaza las capacitaciones presenciales obligatorias", "Apaga incendios por WhatsApp", "Te regala los elementos de protección"] },
      { q: "Simular con IA la evacuación de un edificio sirve para…", a: "Encontrar las mejores rutas de escape y los cuellos de botella", w: ["Dejar de hacer simulacros reales", "Elegir la música de la evacuación", "Decorar las salidas"] },
      { q: "Si la IA detecta una zona peligrosa, ¿quién decide qué medidas tomar?", a: "El responsable de seguridad, con la información de la IA", w: ["La IA, que cierra la zona sola sin avisarle a nadie", "El último que llegó", "Las cámaras, por votación"] },
      { q: "Un dron con cámara térmica e IA en una inspección permite…", a: "Revisar lugares altos o peligrosos sin exponer a personas", w: ["Reemplazar todas las inspecciones presenciales", "Repartir el almuerzo en altura", "Sacar selfies aéreas"] },
      { q: "¿Por qué conviene que la IA analice los \"casi accidentes\"?", a: "Porque muestran riesgos antes de que alguien se lastime", w: ["Porque hay que registrarlos solo por obligación legal", "Porque son divertidos", "Porque la IA se aburre"] },
      { q: "Una IA que mide el ruido en una fábrica puede avisar cuando…", a: "Se superan niveles que dañan la audición", w: ["Hay demasiada gente hablando en el comedor", "Alguien canta desafinado", "Termina el partido"] },
      { q: "¿Qué cuidado hay que tener con las cámaras de IA que monitorean a los trabajadores?", a: "Respetar su privacidad y explicarles para qué se usan", w: ["Ponerlas en todos lados, incluso en los vestuarios, por seguridad", "Usarlas para hacer TikToks", "Ponerles filtro de gatito"] },
      { q: "Una IA te genera un checklist de seguridad para una tarea. ¿Qué hacés?", a: "Lo reviso con un profesional antes de usarlo", w: ["Lo uso tal cual, porque la IA conoce todas las normas", "Lo uso de posavasos", "Lo firmo sin leer y a otra cosa"] },
      { q: "Detectar con visión artificial que alguien entra en una zona con máquinas en movimiento permite…", a: "Frenar la máquina o dar la alerta a tiempo", w: ["Registrar el ingreso para revisarlo al final del día", "Acelerar la máquina para que pase rápido", "Sacarle una foto de recuerdo"] },
      { q: "Un sistema de IA que analiza videos de un trabajador en su puesto puede…", a: "Detectar posturas que pueden causar lesiones", w: ["Medir cuántas piezas produce por hora", "Elegirle la ropa", "Puntuar sus pasos de baile"] },
    ],
  },
  {
    id: "rrhh",
    nombre: "Recursos Humanos",
    emoji: "🤝",
    color: "#8E6CEF",
    preguntas: [
      { q: "Un software con IA que lee cientos de CVs puede…", a: "Ayudar a filtrar candidatos según los requisitos del puesto", w: ["Decidir solo a quién contratar", "Corregirle la ortografía al jefe", "Adivinar el signo de cada candidato"] },
      { q: "¿Qué riesgo tiene usar IA para seleccionar personal?", a: "Que repita sesgos o discriminaciones de los datos con los que aprendió", w: ["Que reciba demasiados CVs", "Que se enamore de un candidato", "Que se quede sin tinta"] },
      { q: "Un chatbot interno de RRHH puede responder…", a: "Consultas sobre vacaciones, licencias y recibos de sueldo", w: ["Pedidos de aumento, aprobándolos al instante", "Quién se comió el yogur de la heladera", "Qué pedir de almuerzo"] },
      { q: "Usar IA para escribir un aviso de búsqueda laboral sirve para…", a: "Redactarlo más rápido, aunque hay que revisarlo", w: ["Asegurar que se postulen los mejores candidatos", "Hacer que el aviso rime", "No hacer entrevistas nunca más"] },
      { q: "La IA puede analizar encuestas de clima laboral para…", a: "Detectar los temas que preocupan a los empleados", w: ["Identificar quién respondió cada encuesta", "Predecir si llueve el viernes", "Elegir el catering"] },
      { q: "¿Qué es un onboarding asistido por IA?", a: "Acompañar a quien entra a la empresa con guías e información automáticas", w: ["Un proceso para evaluar el desempeño anual", "Subir a bordo de un crucero", "Organizar el asado de fin de año"] },
      { q: "Usar datos para predecir qué empleados podrían renunciar es un análisis de…", a: "Rotación de personal", w: ["Clima laboral", "Chusmerío avanzado", "Pronóstico del tiempo"] },
      { q: "¿Quién debe tomar la decisión final de contratar a alguien?", a: "Una persona, usando la IA solo como apoyo", w: ["La IA, porque es más objetiva que las personas", "El candidato, tirando un dado", "Un sorteo en Instagram"] },
      { q: "Una plataforma de capacitación con IA puede…", a: "Recomendar cursos según las habilidades de cada empleado", w: ["Dar el mismo curso a todos, para que sea más justo", "Rendir los exámenes por vos", "Mandarte a dormir la siesta"] },
      { q: "¿Qué datos de los empleados hay que proteger especialmente al usar IA?", a: "Datos personales como sueldo, salud y documentos", w: ["El nombre del puesto de cada uno", "El menú del comedor", "El color de la oficina"] },
      { q: "Un candidato usa IA para mejorar la redacción de su CV. ¿Está mal?", a: "No, está bien si la información es verdadera", w: ["Sí, porque la empresa ya no puede saber cómo es el candidato", "Solo si el CV es rosa", "Sí, los CV se escriben con pluma"] },
      { q: "Las entrevistas por video evaluadas por IA generan debate porque…", a: "Pueden ser injustas si juzgan gestos, acento o apariencia", w: ["Son más caras que las presenciales", "La IA se pone nerviosa", "Se ve el desorden de tu cuarto"] },
      { q: "Con la llegada de la IA, ¿qué habilidad se vuelve más valiosa en RRHH?", a: "La empatía y el trato humano", w: ["Tipear rápido para cargar datos", "Hacer fotocopias en tiempo récord", "Leer la mente"] },
      { q: "¿Qué es \"people analytics\"?", a: "Usar datos para tomar mejores decisiones sobre las personas de la empresa", w: ["Un sistema para controlar la asistencia", "Una red social para chusmear compañeros", "Un curso de interpretación de sueños"] },
      { q: "Si una IA sugiere un rango salarial para un puesto, conviene…", a: "Compararlo con el mercado y las políticas de la empresa", w: ["Usarlo tal cual, porque la IA conoce todos los sueldos", "Duplicarlo y ver qué pasa", "Pagar en figuritas"] },
    ],
  },
  {
    id: "datos",
    nombre: "Ciencia de Datos e IA",
    emoji: "🤖",
    color: "#2F9BD7",
    preguntas: [
      { q: "¿Qué significa \"IA\"?", a: "Inteligencia Artificial", w: ["Información Automatizada", "Internet Asombrosa", "Idea Alocada"] },
      { q: "¿Qué es el machine learning?", a: "Que las computadoras aprendan patrones a partir de datos", w: ["Programar a mano cada regla que sigue la computadora", "Una clase de gimnasia para robots", "Aprender a usar el lavarropas"] },
      { q: "ChatGPT, Claude y Gemini son ejemplos de…", a: "Modelos de lenguaje (LLM)", w: ["Buscadores de internet", "Primos lejanos de R2-D2", "Marcas de heladeras"] },
      { q: "¿Qué es un dataset?", a: "Un conjunto de datos", w: ["Un programa para hacer gráficos", "Un set de tenis para nerds", "Un juego de mesa"] },
      { q: "¿Cuál es el lenguaje de programación más usado en ciencia de datos?", a: "Python", w: ["HTML", "Klingon", "Morse"] },
      { q: "¿Qué es un prompt?", a: "La instrucción o pregunta que le das a una IA", w: ["La respuesta que te da la IA", "Un tipo de pan", "El apodo del robot"] },
      { q: "Cuando una IA inventa una respuesta falsa pero convincente, se dice que…", a: "Alucina", w: ["Se desactualiza", "Sueña con ovejas eléctricas", "Se hace el gracioso"] },
      { q: "Si entrenás una IA con datos sesgados, el resultado probablemente será…", a: "Sesgado también", w: ["Neutral, porque la IA corrige los errores sola", "Más simpático", "Con olor a nuevo"] },
      { q: "¿Qué gráfico conviene para ver cómo cambian las ventas mes a mes?", a: "Un gráfico de líneas", w: ["Un gráfico de torta", "Un dibujo a mano alzada", "Un meme"] },
      { q: "¿Qué hace la visión por computadora?", a: "Permite que la IA interprete imágenes y videos", w: ["Sube la resolución de la pantalla", "Le pone anteojos a la compu", "Limpia la pantalla"] },
      { q: "Separar los datos en \"entrenamiento\" y \"prueba\" sirve para…", a: "Comprobar si el modelo funciona con datos que no vio", w: ["Que el modelo tenga el doble de datos para aprender", "Que los datos no se peleen", "Hacer una fiesta de datos"] },
      { q: "¿Qué es la IA generativa?", a: "IA que crea contenido nuevo: textos, imágenes o música", w: ["IA que solo clasifica datos que ya existen", "IA que genera electricidad", "IA que tiene hijos"] },
      { q: "Antes de analizar datos hay que \"limpiarlos\". ¿Qué significa?", a: "Corregir errores, duplicados y valores faltantes", w: ["Borrar los datos que no nos gustan", "Pasarles un trapo con lavandina", "Meterlos en el lavarropas"] },
      { q: "¿Qué es un algoritmo?", a: "Una serie de pasos para resolver un problema", w: ["Un lenguaje de programación", "El ritmo de un reggaetón", "Un tipo de dinosaurio"] },
      { q: "¿Qué es Big Data?", a: "Volúmenes enormes de datos, difíciles de manejar con herramientas comunes", w: ["Una base de datos muy ordenada", "Una computadora muy grande", "Un dato que va al gimnasio"] },
    ],
  },
];
